# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: UseNode@1
  displayName: 'Set Node.js version'
  inputs:
    version: '12.x'  

- task: Npm@1
  displayName: 'Install Node.js'
  inputs:
    command: 'install'
    workingDir: '$(System.DefaultWorkingDirectory)'

- task: Npm@1
  displayName: 'run JEST tests'
  inputs:
    command: custom
    workingDir: '$(System.DefaultWorkingDirectory)'
    verbose: false
    customCommand: 'run test'

- task: PublishTestResults@2
  displayName: 'Publish Test Results summary-jest-junit.xml'
  inputs:
    testResultsFiles: 'summary-jest-junit.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/__tests__'
    testRunTitle: 'Jest Unit Tests'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage from $(System.DefaultWorkingDirectory)/__tests__/cobertura-coverage.xml'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/__tests__/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/__tests__'
    failIfCoverageEmpty: true

- task: Npm@1
  displayName: 'Build project'
  inputs:
    command: 'custom'
    workingDir: '$(System.DefaultWorkingDirectory)'
    customCommand: 'run build'
  env:
    PUBLIC_SITE_URL: $(PUBLIC_SITE_URL)
    DISQUS_SHORT_NAME: $(DISQUS_SHORT_NAME)
    AZURE_TABLE_SERVICE_URL: $(AZURE_TABLE_SERVICE_URL)
    AZURE_FUNC_PLATE_RECOGNIZER_URL: $(AZURE_FUNC_PLATE_RECOGNIZER_URL)
    AZURE_FUNC_PLATE_RECOGNIZER_TOKEN: $(AZURE_FUNC_PLATE_RECOGNIZER_TOKEN)
    AZURE_FUNC_PLATE_RECOGNIZER_EXTERNAL_SERVICE_URL: $(AZURE_FUNC_PLATE_RECOGNIZER_EXTERNAL_SERVICE_URL)
    AZURE_TABLE_FAVORITES_SERVICE_URL: $(AZURE_TABLE_FAVORITES_SERVICE_URL)
    AZURE_TABLE_FAVORITES_SERVICE_URL_QUERY: $(AZURE_TABLE_FAVORITES_SERVICE_URL_QUERY)
    AZURE_PLATESMANIA_PROXY: $(AZURE_PLATESMANIA_PROXY)
    AZURE_APP_INSIGHTS_KEY: $(AZURE_APP_INSIGHTS_KEY)
    PLATES_MANIA_KEY: $(PLATES_MANIA_KEY)
    RIA_KEY: $(RIA_KEY)
    FACEBOOK_CLIENT_ID: $(FACEBOOK_CLIENT_ID)
    FACEBOOK_APP_SECRET: $(FACEBOOK_APP_SECRET)
    GOOGLE_CLIENT_ID: $(GOOGLE_CLIENT_ID)
    GOOGLE_APP_SECRET: $(GOOGLE_APP_SECRET)


# - task: DownloadSecureFile@1
#   inputs:
#     secureFile: deploy_key
#   displayName: 'Get the deploy key'

# - script: |
#     mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
#     chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
#     ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
#     git remote set-url --push origin git@github.com:krak86.github.io/carplates.io.git
#     git push origin HEAD:master
#   displayName: 'Publish GitHub Pages'
#   condition: |
#     and(not(eq(variables['Build.Reason'], 'PullRequest')),
#         eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: ArchiveFiles@2
  displayName: 'Archive sources'
  inputs:
    rootFolderOrFile: $(Build.SourcesDirectory)
    includeRootFolder: false

- task: CopyFiles@2
  displayName: 'Copy ARM templates'
  inputs:
    SourceFolder: deployment
    Contents: '*.json'
    TargetFolder: $(build.artifactstagingdirectory)/Templates

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'