name: Node CI
on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.1.0]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, test, and build
      run: |
        npm install
        npm test
        npm run build
